# Generated by Django 5.2 on 2025-04-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panchayath', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_panchayathward',
        ),
    ]
