# Generated by Django 4.2.16 on 2025-02-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_ward',
            name='ward_number',
            field=models.CharField(max_length=50),
        ),
    ]
