# Generated by Django 4.2.16 on 2025-02-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_alter_tbl_ward_ward_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_ward',
            name='ward_number',
            field=models.IntegerField(),
        ),
    ]
