# Generated by Django 4.2.16 on 2025-01-30 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_place'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_panchayath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panchayath_id', models.CharField(max_length=50)),
                ('panchayath_name', models.CharField(max_length=50)),
                ('panchayath_email', models.CharField(max_length=50)),
                ('panchayath_contact', models.CharField(max_length=50)),
                ('panchayath_address', models.CharField(max_length=50)),
                ('panchayath_password', models.CharField(max_length=50)),
                ('panchayath_status', models.CharField(max_length=50)),
                ('panchayath_photo', models.FileField(upload_to='Assets/panchayath/photo/')),
                ('panchayath_proof', models.FileField(upload_to='Assets/panchayath/proof/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
