# Generated by Django 4.2.16 on 2025-02-11 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_panchayath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_panchayath',
            name='panchayath_status',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='tbl_paliativecare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paliativecare_name', models.CharField(max_length=50)),
                ('paliativecare_email', models.CharField(max_length=50)),
                ('paliativecare_contact', models.CharField(max_length=50)),
                ('paliativecare_address', models.CharField(max_length=50)),
                ('paliativecare_photo', models.FileField(upload_to='')),
                ('paliativecare_proof', models.FileField(upload_to='')),
                ('paliativecare_password', models.CharField(max_length=50)),
                ('paliativecare_status', models.IntegerField(default=0)),
                ('panchayath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_panchayath')),
            ],
        ),
    ]
