# Generated by Django 4.2.16 on 2025-02-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_alter_tbl_panchayath_panchayath_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_paliativecare',
            name='paliativecare_photo',
            field=models.FileField(upload_to='Assets/paliativecare/photo/'),
        ),
        migrations.AlterField(
            model_name='tbl_paliativecare',
            name='paliativecare_proof',
            field=models.FileField(upload_to='Assets/paliativecare/photo/'),
        ),
    ]
