# Generated by Django 4.2.16 on 2025-02-13 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_alter_tbl_paliativecare_paliativecare_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_panchayath',
            name='panchayath_id',
        ),
    ]
