# Generated by Django 4.2.16 on 2025-02-20 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_alter_tbl_ward_ward_number'),
        ('Guest', '0005_remove_tbl_panchayath_panchayath_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_reg',
            name='place',
        ),
        migrations.AddField(
            model_name='tbl_reg',
            name='panchayath',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_panchayath'),
        ),
        migrations.AddField(
            model_name='tbl_reg',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_ward'),
        ),
    ]
