# Generated by Django 4.2.16 on 2025-02-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_remove_tbl_reg_place_tbl_reg_panchayath_tbl_reg_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_reg',
            name='user_photo',
            field=models.FileField(default='Assets/user/photo/img.jpg', null=True, upload_to='Assets/user/photo/'),
        ),
    ]
