# Generated by Django 5.2 on 2025-04-18 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_alter_tbl_ward_ward_number'),
        ('Guest', '0007_alter_tbl_reg_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_panchayathward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panchayath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_panchayath')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_ward')),
            ],
        ),
    ]
