# Generated by Django 5.2 on 2025-04-18 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_tbl_panchayathward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_reg',
            name='panchayath',
        ),
        migrations.AlterField(
            model_name='tbl_reg',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_panchayathward'),
        ),
    ]
