# Generated by Django 4.2.16 on 2025-02-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_patient',
            name='patient_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tbl_patient',
            name='patient_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
    ]
