# Generated by Django 4.2.16 on 2025-02-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_tbl_patient_patient_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_patient',
            name='patient_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
