# Generated by Django 4.2.16 on 2025-03-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_tbl_patient_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_request',
            name='request_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
