# Generated by Django 4.2.16 on 2025-03-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_tbl_request_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_request',
            name='request_status',
            field=models.IntegerField(default=0),
        ),
    ]
