# Generated by Django 4.2.16 on 2025-03-24 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_tbl_request_request_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rating',
        ),
    ]
