# Generated by Django 4.2.16 on 2025-03-24 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_alter_tbl_reg_user_photo'),
        ('User', '0010_tbl_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_rating',
            name='paliativecare_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_paliativecare'),
        ),
    ]
