# Generated by Django 5.0.6 on 2025-04-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_remove_tbl_rating_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='request_team',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbl_request',
            name='request_description',
            field=models.CharField(max_length=150),
        ),
    ]
